# Generated by Django 4.1.5 on 2023-01-25 09:07

from django.db import migrations, models
import django.db.models.deletion
import temp_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(upload_to=temp_image.models.user_directory_path),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.member",
                    ),
                ),
            ],
            options={
                "db_table": "temp_image",
                "managed": True,
            },
        ),
    ]
