# Generated by Django 3.2.16 on 2023-02-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsgroup',
            name='board_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
