# Generated by Django 4.1.5 on 2023-01-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disease", "0001_initial"),
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantsByDisease",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.board"
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease",
                    ),
                ),
            ],
            options={"db_table": "plants_by_disease", "managed": True,},
        ),
    ]
