# Generated by Django 4.1.5 on 2023-01-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_board_plant_group_alter_board_user"),
        ("disease", "0001_initial"),
        ("plants_by_disease", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantsbydisease",
            name="board",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="board.board"
            ),
        ),
        migrations.AlterField(
            model_name="plantsbydisease",
            name="disease",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="disease.disease",
            ),
        ),
    ]
