# Generated by Django 3.2.16 on 2023-02-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0004_alter_board_input_image_alter_board_output_image'),
        ('member', '0004_remove_member_board_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLikeByUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_delete', models.CharField(default='0', max_length=1)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'board_like_by_user',
                'managed': True,
            },
        ),
    ]
