# Generated by Django 4.1.5 on 2023-01-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("is_staff", models.CharField(default="0", max_length=1)),
                ("is_delete", models.CharField(default="0", max_length=1)),
                ("email", models.EmailField(max_length=256)),
            ],
            options={"db_table": "user", "managed": True,},
        ),
    ]
