# Generated by Django 4.1.5 on 2023-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=150)),
                ("visited", models.CharField(default="0", max_length=1)),
                ("name", models.CharField(max_length=150)),
                ("is_staff", models.CharField(default="0", max_length=1)),
            ],
            options={"db_table": "user", "managed": True,},
        ),
    ]
