# Generated by Django 4.1.5 on 2023-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="board_cnt",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
