# Generated by Django 4.1.5 on 2023-01-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_delete',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
