# Generated by Django 4.1.5 on 2023-01-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='0', max_length=256),
        ),
    ]
