# Generated by Django 3.2.16 on 2023-02-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_board_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='board_cnt',
        ),
    ]
