# Generated by Django 4.1.5 on 2023-01-04 06:03

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("explain", models.CharField(max_length=500)),
                ("user_key", models.IntegerField()),
                (
                    "image",
                    models.ImageField(upload_to=board.models.user_directory_path),
                ),
                ("result", models.ImageField(upload_to="")),
                ("date", models.DateTimeField()),
                ("views", models.IntegerField()),
                ("like", models.IntegerField()),
                ("disease", models.CharField(max_length=100)),
                ("growth", models.CharField(max_length=100)),
                ("is_delete", models.IntegerField()),
            ],
            options={"db_table": "board", "managed": True,},
        ),
    ]
