# Generated by Django 4.1.5 on 2023-01-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="is_writing",
            field=models.CharField(default="1", max_length=1),
        ),
    ]
