# Generated by Django 4.1.5 on 2023-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="test_column",
            field=models.CharField(default="", max_length=100),
        ),
    ]
