# Generated by Django 4.1.5 on 2023-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="output_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
