# Generated by Django 4.1.5 on 2023-01-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_board_is_writing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="is_writing",
        ),
    ]
