# Generated by Django 4.1.5 on 2023-01-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants_group", "0002_alter_plantsgroup_user"),
        ("member", "0001_initial"),
        ("board", "0002_alter_board_output_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="plant_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plants_group.plantsgroup",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.member",
            ),
        ),
    ]
