# Generated by Django 4.1.5 on 2023-01-04 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_test_column"),
    ]

    operations = [
        migrations.RemoveField(model_name="board", name="test_column",),
        migrations.AlterField(
            model_name="board",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="board",
            name="disease",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="growth",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="is_delete",
            field=models.CharField(default="0", max_length=1),
        ),
        migrations.AlterField(
            model_name="board", name="like", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="board",
            name="result",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="board", name="views", field=models.IntegerField(default=0),
        ),
    ]
