# Generated by Django 4.1.5 on 2023-01-24 11:52

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_board_plant_group_alter_board_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="output_image",
            field=models.ImageField(upload_to=board.models.user_directory_path),
        ),
    ]
