# Generated by Django 4.1.5 on 2023-01-28 07:02

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_remove_board_is_writing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="input_image",
            field=models.ImageField(
                null=True, upload_to=board.models.user_directory_path_input
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="output_image",
            field=models.FileField(
                null=True, upload_to=board.models.user_directory_path_output
            ),
        ),
    ]
