# Generated by Django 4.1.5 on 2023-01-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_is_delete'),
        ('board', '0003_remove_board_test_column_alter_board_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user_key',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
