# Generated by Django 4.1.5 on 2023-01-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_remove_board_user_key_board_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
