# Generated by Django 4.1.5 on 2023-01-06 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_alter_board_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
