# Generated by Django 4.1.5 on 2023-01-09 06:30

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=board.models.koreaTime),
        ),
    ]
